### PR TITLE
Remove `<picture>` wrapper from YouTube embed

### PR DESCRIPTION
**Pull request by nschonni**

### CODE REVIEW

**Comment by nschonni** [comment]
I used the web rebase, so you'll need to squash/merge

**Comment by ethomson** [comment]
Thanks!

**Comment by ethomson** [comment]
Hmm, I reverted this as it no longer lined up in the same place.  I may have screwed something up, please do reopen if I did something wrong.

**Comment by nschonni** [comment]
I'll try and take a look later. I removed it because it doesn't pass HTML validation since `<picture>` doesn't allow this child elements

**Pull request merged**
